# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "learn_nbdev.ipynb"}

modules = ["core.py"]

doc_url = "https://userbz.github.io/learn_nbdev/"

git_url = "https://github.com/userbz/learn_nbdev/tree/master/"

def custom_doc_links(name): return None
